In [1]:
import numpy as np

In [5]:
"""
Computing reciprocals in loops
"""

def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
        
    return output

values = np.random.randint(1, 10, size = 5)
print(values)

[4 3 2 8 8]


In [16]:
"""
Comparison : Loop vs ufuncs(vectorized)
"""

big_array = np.random.randint(1, 100, size = 1000000)

# %timeit은 쥬피터에서 제공해주는 기능 /// 실행시간 얼마나 걸리는지 알려줌
%timeit compute_reciprocals(big_array)

1.87 s ± 6.41 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [17]:
%timeit 1 / big_array

2.72 ms ± 87.6 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [12]:
"""
Numpy.ufunc
"""

np.random.seed(1)
arr1= np.random.randint(10,size=5)
arr2= np.random.randint(10,size=5)
print(arr1,arr2)

arr1= arr1-2
print(arr1,arr2)

arr3= arr1+arr2
print(arr3)

arr4=np.random.randint(10,size=(3,5))
print(arr4)

[5 8 9 5 0] [0 1 7 6 9]
[ 3  6  7  3 -2] [0 1 7 6 9]
[ 3  7 14  9  7]
[[2 4 5 2 4]
 [2 4 7 7 9]
 [1 7 0 6 9]]


In [17]:
"""
UFuncs: Array Arithmetic
"""

x= np.arange(4)
print("x = ",x)
print("x + 5 = ",x+5)
print("x - 5 = ",x-5)
print("x * 2 = ", x*2)
print("x / 2 = ", x/2)
print("x ** 2 = ", x**2,'\n')
print("x + 5 = ",np.add(x,5))
print("x - 5 = ",np.subtract(x,5))
print("x * 2 = ", np.multiply(x,2))
print("x / 2 = ", np.divide(x,2))
print("x ** 2 = ", np.power(x,2))


x =  [0 1 2 3]
x + 5 =  [5 6 7 8]
x - 5 =  [-5 -4 -3 -2]
x * 2 =  [0 2 4 6]
x / 2 =  [0.  0.5 1.  1.5]
x ** 2 =  [0 1 4 9] 

x + 5 =  [5 6 7 8]
x - 5 =  [-5 -4 -3 -2]
x * 2 =  [0 2 4 6]
x / 2 =  [0.  0.5 1.  1.5]
x ** 2 =  [0 1 4 9]


In [21]:
"""
UFuncs : Absolute Value
"""

x= np.array([-2,-1,9,1,3])
print(np.abs(x))

x= np.array([3-4j, 4-3j, 2+0j, 0+1j])
print(np.abs(x))

[2 1 9 1 3]
[5. 5. 2. 1.]


In [33]:
"""
UFuncs: Trigonometric Functions
"""

theta = np.linspace(0, np.pi, 3)

print(theta)
print(np.sin(theta))
print(np.cos(theta))
print(np.tan(theta))

x= np.linspace(0, 100, 6)
print(x)

[0.         1.57079633 3.14159265]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]
[  0.  20.  40.  60.  80. 100.]


In [37]:
"""
UFuncs: Aggression
"""

x= np.arange(1, 5)
print(x)
aggr = np.add.reduce(x)
print(aggr)

aggr = np.multiply.reduce(x)
print(aggr)

[1 2 3 4]
10
24


In [40]:
# accumulate()
print(x)

accum= np.add.accumulate(x)
print(accum)

accum= np.multiply.accumulate(x)
print(accum)

[1 2 3 4]
[ 1  3  6 10]
[ 1  2  6 24]


In [43]:
# Summing the Values in an Array

np.random.seed(22)
arr= np.random.rand(1000000)
print(arr)

[0.20846054 0.48168106 0.42053804 ... 0.06543463 0.80534246 0.27317008]


In [44]:
%timeit sum(arr)

99.5 ms ± 1.87 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [45]:
%timeit np.sum(arr)

385 µs ± 20.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [51]:
# Other Aggr. functions

print("max = ",np.max(arr))
print("min = ",np.min(arr))
print("mean = ",np.mean(arr))
print("median = ", np.median(arr))
print("percentile =", np.percentile(arr,90))

print(np.any(arr>0))
print(np.all(arr<0))

max =  0.9999996464057614
min =  1.7499423032862893e-06
mean =  0.5000365341903944
median =  0.5005147047331882
percentile = 0.8999537108441031
True
False


In [53]:
# Multi dimensional aggregates

np.random.seed(5)
arr =np.random.randint(10, size=(3,4))
print(arr)

print(np.sum(arr, axis=0))

[[3 6 6 0]
 [9 8 4 7]
 [0 0 7 1]]
[12 14 17  8]
