In [3]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [12]:
lst=[1,2,3,4]

arr=np.array(lst)
print(arr)

[1 2 3 4]


In [13]:
# .dtype attribute

print(arr.dtype)

int32


In [18]:
"""
Size Comparison of ndrray and list objects
"""
from sys import getsizeof

lst = [1,2,3,4,5]
print(getsizeof(lst))

arr = np.array(lst)
print(getsizeof(arr))

96
124


In [19]:
"""
Operations with Numpy Arrays
"""
prices = [30,15,24,16,65,34,6,324]

new_prices = [price-5 for price in prices]
print(new_prices)

# With a ndarray

prices_arr= np.array(prices)
prices_arr = prices_arr - 5
print(prices_arr)

[25, 10, 19, 11, 60, 29, 1, 319]
[ 25  10  19  11  60  29   1 319]


In [31]:
"""
Exercise: Test Scores
"""

test_1 = np.array([92, 94, 88, 91, 87])
test_2 = np.array([79, 100, 86, 93, 91])
test_3 = np.array([87, 85, 72, 90, 92])

test_3_fixed = test_3 + 2
print(test_3_fixed)

total_grades = test_1 + test_2 + test_3
print(total_grades)

final_grade = total_grades / 3
print(final_grade)

jeremy_test_2 = test_2[3]
print(jeremy_test_2)

manual_adwoa_test_1 = np.array([test_1[1], test_1[2]])
print(manual_adwoa_test_1)

[89 87 74 92 94]
[258 279 246 274 270]
[86.         93.         82.         91.33333333 90.        ]
93
[94 88]


In [32]:
student_scores = np.array([test_1, test_2, test_3])
print(student_scores)

print(student_scores[2, 0])

print(student_scores[: ,4])

[[ 92  94  88  91  87]
 [ 79 100  86  93  91]
 [ 87  85  72  90  92]]
87
[87 91 92]


In [34]:
"""
Logical Operations with Arrays
"""
# masking
a = np.array([1,3,4,5,5,6,67,7,8,9])
mask = a > 5
print(mask)

# select using logical operations
selected = a[a>5]
print(selected)

# combined Logical operations | &
selected = a[(a>6) | (a<4)]
print(selected)

selected = a[(a > 4) & (a<7)]
print(selected)

[False False False False False  True  True  True  True  True]
[ 6 67  7  8  9]
[ 1  3 67  7  8  9]
[5 5 6]


In [ ]:
"""
Exercise : Goldillocks Porridge Festival
"""

porridge = np.array([79, 65, ])